---

- name: OPNsense Preapare - Add Ansible User (1/2)
  xml:
    path: "/tmp/qemu_{{ hetzner_pve_opnsense_vm_settings.id }}_vfat/conf/config.xml"
    xpath: /opnsense/system/user[name/text()="{{ item.0.name }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_user | default([]) }}"
    - settings
  when: item.1.value is defined
  no_log: true

- name: OPNsense Preapare - Add Ansible User (2/2)
  xml:
    path: "/tmp/qemu_{{ hetzner_pve_opnsense_vm_settings.id }}_vfat/conf/config.xml"
    xpath: /opnsense/system/user[name/text()="{{ item.0.name }}"]/{{ item.1.key }}
    value: "{{ item.1.b64_value | b64encode }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_user | default([]) }}"
    - settings
  when: item.1.b64_value is defined
  no_log: true

- name: OPNsense Preapare - Add Ansible User to admins
  xml:
    path: "/tmp/qemu_{{ hetzner_pve_opnsense_vm_settings.id }}_vfat/conf/config.xml"
    xpath: /opnsense/system/group[name/text()="{{ item.0.name }}"]
    add_children:
      - member: "{{ item.1.member }}"
    pretty_print: true
  with_subelements:
    - "{{ opn_group }}"
    - settings
