- name: rescue
  hosts: vmhost
  gather_facts: false
  tasks:
    - name: HETZNER - Add SSH key
      community.hrobot.ssh_key:
        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
        state: present
        name: ansible - hetzner_pve
        public_key: "{{ hetzner_pve_ssh_keys.0 }}"
      delegate_to: localhost

    - name: HETZNER - Get all SSH Keys
      community.hrobot.ssh_key_info:
        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
      register: ssh_keys
      delegate_to: localhost

    - name: HETZNER - Enable a rescue system (64bit Linux) for the next boot
      community.hrobot.boot:
        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
        server_number: "{{ ENV_INVENTORY_SRV_NO }}"
        rescue:
          os: linux
          authorized_keys: "{{ ssh_keys.ssh_keys | map(attribute='fingerprint') | list }}"
      delegate_to: localhost

    - name: HETZNER - Reset SERVER
      community.hrobot.reset:
        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
        server_number: "{{ ENV_INVENTORY_SRV_NO }}"
        reset_type: hardware
      delegate_to: localhost

    - name: Wait for system comming up after activating Rescue
      ansible.legacy.wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 10
      delegate_to: localhost

  roles:
    - { role: '../roles/hetzner_pve', tags: ['skip'] }
