# add here bits and pieces you want to isolate and test-out. To have access to variables, etc. leave the roles below in place
- name: test
  hosts: vmhost
  user: root
  gather_facts: false
  tasks:
#    - ansible.builtin.setup:

#    - name: Set public key
#      ansible.legacy.set_fact:
#        hetzner_pve_ssh_keys:
#          - "{{ lookup('file', '~/.ssh/id_ed25519_ansible.pub') }}"
#      when: hetzner_pve_ssh_keys is defined and (hetzner_pve_ssh_keys | length==0)

#    - name: HETZNER - Add SSH key
#      community.hrobot.ssh_key:
#        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
#        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
#        state: present
#        name: ansible - hetzner_pve
#        public_key: "{{ hetzner_pve_ssh_keys.0 }}"
#      delegate_to: localhost

#    - name: HETZNER - Get all SSH Keys
#      community.hrobot.ssh_key_info:
#        hetzner_user: "{{ hetzner_pve_hetzner_api_user }}"
#        hetzner_password: "{{ hetzner_pve_hetzner_api_pass }}"
#      register: ssh_keys
#      delegate_to: localhost

    - name: OPNsense - Resize disk
      ansible.builtin.shell: qm resize {{ hetzner_pve_opnsense_vm_settings.id }} scsi0 {{ hetzner_pve_opnsense_vm_settings.disk_size }}


#    - name: OPNsense Preapare - Get ansible host IP for setup OPNsense
#      community.general.ipify_facts.ipify_facts:
#      register: public_ip
#      connection: local
#    - name: print
#      debug:
#        msg: echo {{ public_ip }}

  roles:
    - { role: '../roles/hetzner_pve', tags: ['skip'] }
